name: Build and publish

on:
  push:
    branches:
      - main
    paths:
      - packages/swagger

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - run: npm ci

      - run: npm test
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      - run: npm run build -w packages/swagger
      - run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
      - run: npm publish -w packages/swagger --access public
