name: Build and publish create-api-docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "packages/create-api-docs/**"

jobs:
  build_and_publish:
    uses: ./.github/workflows/publish.yml
    with:
      workspace: packages/create-api-docs
    secrets: 
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
